# coding: utf-8

"""
    OpenFEC

    This API allows you to explore the way candidates and committees fund their campaigns.    The FEC API is a RESTful web service supporting full-text and field-specific searches on FEC data. [Bulk downloads](https://www.fec.gov/data/advanced/?tab=bulk-data) are available on the current site. Information is tied to the underlying forms by file ID and image ID. Data is updated nightly.    There is a lot of data, but a good place to start is to use search to find interesting candidates and committees. Then, you can use their IDs to find report or line item details with the other endpoints. If you are interested in individual donors, check out contributor information in schedule_a.    Get an [API key here](https://api.data.gov/signup/). That will enable you to place up to 1,000 calls an hour. Each call is limited to 100 results per page. You can email questions, comments or a request to get a key for 120 calls per minute to [APIinfo@fec.gov](mailto:apiinfo@fec.gov). You can also ask questions and discuss the data in the [FEC data Google Group](https://groups.google.com/forum/#!forum/fec-data). API changes will also be added to this group in advance of the change.    The model definitions and schema are available at [/swagger](/swagger/). This is useful for making wrappers and exploring the data.    A few restrictions limit the way you can use FEC data. For example, you can’t use contributor lists for commercial purposes or to solicit donations. [Learn more here](https://www.fec.gov/updates/sale-or-use-contributor-information/).    [View our source code](https://github.com/fecgov/openFEC). We welcome issues and pull requests!  # noqa: E501

    OpenAPI spec version: 1.0

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.efiling_api import EfilingApi  # noqa: E501
from swagger_client.rest import ApiException


class TestEfilingApi(unittest.TestCase):
    """EfilingApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.efiling_api.EfilingApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_efile_filings_get(self):
        """Test case for efile_filings_get

        """
        pass

    def test_efile_reports_house_senate_get(self):
        """Test case for efile_reports_house_senate_get

        """
        pass

    def test_efile_reports_pac_party_get(self):
        """Test case for efile_reports_pac_party_get

        """
        pass

    def test_efile_reports_presidential_get(self):
        """Test case for efile_reports_presidential_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
