---
name: Package and Upload to PyPi

on:
  release:
    types:
      - created

jobs:
  build:
    name: Build and publish to PyPi
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: setup python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install latest pip, setuptools + tox
      run: |
        python -m pip install --upgrade pip setuptools twine wheel
        python -m pip install -r requirements.txt

    - name: Build wheels
      run: |
        export TAG=$(curl https://api.github.com/repos/rhythmictech/openFEC-python-sdk/releases/latest | jq -r .tag_name)
        python setup.py bdist_wheel
        python setup.py sdist

    - name: Upload Dist
      uses: actions/upload-artifact@v1
      with:
        name: wheel
        path: dist/

    - name: Publish package
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.PYPI_ACCOUNT_TOKEN }}
